version: "3"

services:
  api:
    image: cactushub/pdf_generator_api
    container_name: "pdf_generator_api"
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    ports: 
        -  "5000:5000"
    volumes: 
        - ./src:/code/src:rw
    command: gunicorn -b 0.0.0.0:5000 app
    networks: 
      default:
        ipv4_address: 172.19.0.3

  nginx:
    image: cactushub/pdf_generator_web
    container_name: "pdf_generator_web"
    env_file: ./nginx/.env
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
        -  "5001:80"
    volumes: 
        -  ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        -  "api"
    tty: true
    networks: 
      default:
        ipv4_address: 172.19.0.4

networks: 
  default:
    driver: bridge
    ipam:
      config: 
        - subnet: 172.19.0.0/16